### ISSUE TITLE
ErrorData 不能为其命名  ts(4023)

### ISSUE THREAD

**Issue by tedteddy** [BobbyLH/ajax-maker#1]
当`tsconfig`中配置`declaration: true`, `request` 报错
`const request: (options: Options) => PromiseWrapper<ResObj, ResObj, ResObj, ErrorRes>`
**ErrorData 不能为其命名 ts(4023)**

**Comment by BobbyLH** [comment]
谢谢，目前该问题已修复
https://github.com/BobbyLH/ajax-maker/commit/a94a5d4bd0fbe8af9c55517c19812abe8a862216
